"""
PRAXIS Adapter — Aider (Tier 3)
=================================
Detects: `aider` in PATH OR .aider.conf.yml in project root.
Injects: CONVENTIONS.md + updates .aider.conf.yml to read it.

Aider reads CONVENTIONS.md automatically when configured via read: directive.

Python 3.8+. Zero external dependencies.
"""

from __future__ import annotations

import shutil
from pathlib import Path
from typing import Any, Dict, List

from .base import PraxisAdapter, _write_file, _remove_file

_MARKER = "<!-- PRAXIS-GOVERNANCE -->"

_CONVENTIONS_HEADER = """\
<!-- PRAXIS-GOVERNANCE -->
# CONVENTIONS.md — PRAXIS Governance Active

> **PRAXIS Research Study**: This workspace participates in the PRAXIS AI
> governance rules injected via `praxis activate`.
>
> Log tasks: `praxis log "desc" -d MIN -m MODEL -q 1-5 -i N -h N`
> Log governance events: `praxis govern "description"`

"""

_AIDER_CONF_PRAXIS = """\

# PRAXIS governance — added by praxis activate
read:
  - CONVENTIONS.md
"""

_AIDER_CONF_DEFAULT = """\
# Aider configuration — generated by PRAXIS Universal Kit
# See: https://aider.chat/docs/config.html

# Read CONVENTIONS.md for project governance conventions
read:
  - CONVENTIONS.md

# Model settings (customize as needed)
# model: claude-sonnet-4-6
"""


class AiderAdapter(PraxisAdapter):
    """PRAXIS adapter for Aider CLI coding agent (Tier 3)."""

    PLATFORM_ID = "aider"

    def detect(self) -> bool:
        cwd = Path.cwd()
        if (cwd / ".aider.conf.yml").is_file():
            return True
        if (cwd / ".aider.conf.yaml").is_file():
            return True
        if (cwd / "CONVENTIONS.md").is_file():
            return True
        return shutil.which("aider") is not None

    def inject_governance(
        self,
        templates_dir: Path,
        workspace_dir: Path,
    ) -> List[str]:
        created: List[str] = []

        # 1. Create / update CONVENTIONS.md
        soul = self._soul(templates_dir, workspace_dir)
        agents = self._agents(templates_dir, workspace_dir)
        conventions_content = (
            _CONVENTIONS_HEADER
            + soul
            + "\n\n---\n\n## Operational Procedures\n\n"
            + agents
        )

        conventions_dest = workspace_dir / "CONVENTIONS.md"
        if conventions_dest.is_file():
            existing = conventions_dest.read_text(encoding="utf-8")
            if _MARKER not in existing:
                conventions_dest.write_text(
                    existing.rstrip() + "\n\n" + conventions_content,
                    encoding="utf-8",
                )
                created.append(f"{conventions_dest} (updated)")
        else:
            _write_file(conventions_dest, conventions_content)
            created.append(str(conventions_dest))

        # 2. Update .aider.conf.yml to include read: CONVENTIONS.md
        conf_path = workspace_dir / ".aider.conf.yml"
        if conf_path.is_file():
            existing_conf = conf_path.read_text(encoding="utf-8")
            if "# PRAXIS governance" not in existing_conf and "CONVENTIONS.md" not in existing_conf:
                conf_path.write_text(existing_conf + _AIDER_CONF_PRAXIS, encoding="utf-8")
                created.append(f"{conf_path} (updated)")
        else:
            _write_file(conf_path, _AIDER_CONF_DEFAULT)
            created.append(str(conf_path))

        return created

    def remove_governance(self, workspace_dir: Path) -> List[str]:
        removed: List[str] = []

        # Remove CONVENTIONS.md if PRAXIS-created
        conventions = workspace_dir / "CONVENTIONS.md"
        if conventions.is_file():
            text = conventions.read_text(encoding="utf-8")
            if text.strip().startswith(_MARKER):
                result = _remove_file(conventions)
                if result:
                    removed.append(result)

        # Clean .aider.conf.yml — remove PRAXIS block
        conf = workspace_dir / ".aider.conf.yml"
        if conf.is_file():
            text = conf.read_text(encoding="utf-8")
            if "# PRAXIS governance" in text:
                cleaned = text.split("\n# PRAXIS governance")[0]
                if cleaned.strip():
                    conf.write_text(cleaned, encoding="utf-8")
                    removed.append(f"{conf} (governance section removed)")
                else:
                    result = _remove_file(conf)
                    if result:
                        removed.append(result)

        return removed

    def get_info(self) -> Dict[str, Any]:
        return {
            "id": self.PLATFORM_ID,
            "name": "Aider",
            "tier": 3,
            "description": "Injects PRAXIS governance into CONVENTIONS.md for Aider.",
            "governance_files": ["CONVENTIONS.md", ".aider.conf.yml"],
            "instructions": (
                "CONVENTIONS.md has been created with PRAXIS governance rules. "
                ".aider.conf.yml has been updated to load it automatically. "
                "Aider will include CONVENTIONS.md in context every session."
            ),
        }
