"""
PRAXIS Adapter — Generic (Tier 4 — Universal Fallback)
=======================================================
Always available. Works with any AI tool: ChatGPT, Gemini, Perplexity, etc.
Injects PRAXIS_GOVERNANCE.md in the project root.

User pastes the file's content into their AI tool's system prompt or
custom instructions panel. No automatic detection required.

Python 3.8+. Zero external dependencies.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any, Dict, List

from .base import PraxisAdapter, _write_file, _remove_file

_MARKER = "<!-- PRAXIS-GOVERNANCE -->"

_GOVERNANCE_HEADER = """\
<!-- PRAXIS-GOVERNANCE -->
# PRAXIS Governance Framework

> **PRAXIS Research Study**: This file was generated by `praxis activate`.
> Copy its content into your AI tool's system prompt or custom instructions.
>
> Log tasks: `praxis log "desc" -d MIN -m MODEL -q 1-5 -i N -h N`
> Log governance events: `praxis govern "description"`

"""


class GenericAdapter(PraxisAdapter):
    """PRAXIS fallback adapter for any AI tool (Tier 4)."""

    PLATFORM_ID = "generic"

    def detect(self) -> bool:
        """Generic adapter is always available — it is the fallback."""
        return True

    def inject_governance(
        self,
        templates_dir: Path,
        workspace_dir: Path,
    ) -> List[str]:
        created: List[str] = []
        dest = workspace_dir / "PRAXIS_GOVERNANCE.md"

        soul = self._soul(templates_dir, workspace_dir)
        agents = self._agents(templates_dir, workspace_dir)
        content = (
            _GOVERNANCE_HEADER
            + soul
            + "\n\n---\n\n## Operational Procedures\n\n"
            + agents
        )

        if dest.is_file():
            existing = dest.read_text(encoding="utf-8")
            if _MARKER in existing:
                return []
            dest.write_text(existing.rstrip() + "\n\n" + content, encoding="utf-8")
            created.append(f"{dest} (updated)")
        else:
            _write_file(dest, content)
            created.append(str(dest))

        return created

    def remove_governance(self, workspace_dir: Path) -> List[str]:
        removed: List[str] = []
        dest = workspace_dir / "PRAXIS_GOVERNANCE.md"
        if not dest.is_file():
            return removed

        text = dest.read_text(encoding="utf-8")
        if _MARKER in text:
            if text.strip().startswith(_MARKER):
                result = _remove_file(dest)
                if result:
                    removed.append(result)
            else:
                idx = text.find("\n\n" + _MARKER)
                if idx != -1:
                    dest.write_text(text[:idx], encoding="utf-8")
                    removed.append(f"{dest} (governance section removed)")

        return removed

    def get_info(self) -> Dict[str, Any]:
        return {
            "id": self.PLATFORM_ID,
            "name": "Generic (any AI tool)",
            "tier": 4,
            "description": (
                "Universal fallback. Works with ChatGPT, Gemini, Perplexity, "
                "or any AI tool that accepts a system prompt."
            ),
            "governance_files": ["PRAXIS_GOVERNANCE.md"],
            "instructions": (
                "PRAXIS_GOVERNANCE.md has been created. "
                "Open it and paste its contents into your AI tool's "
                "system prompt or custom instructions panel."
            ),
        }
