"""
PRAXIS Adapter — OpenClaw (Tier 1 — Deep Integration)
======================================================
Detects: ~/.openclaw/ directory OR `openclaw` in PATH OR $OPENCLAW_HOME.
Injects: SOUL.md + AGENTS.md + HEARTBEAT.md + MEMORY.md in workspace root.

Tier 1: deepest integration. Supports cron reminders, heartbeat passive
collection. Memory system maps directly to PRAXIS L4.

Python 3.8+. Zero external dependencies.
"""

from __future__ import annotations

import os
import shutil
import subprocess
from pathlib import Path
from typing import Any, Dict, List

from .base import PraxisAdapter, _write_file, _remove_file

_MARKER = "<!-- PRAXIS-GOVERNANCE -->"

_HEARTBEAT_CONTENT = """\
<!-- PRAXIS-GOVERNANCE -->
# PRAXIS Heartbeat Protocol — OpenClaw L1 Integration

## Purpose
Passive session monitoring for PRAXIS research metrics.
OpenClaw heartbeat maps to PRAXIS L4 (cross-session persistence).

## Events to Track
- Session start / end timestamps
- AI tool invocations (count only)
- File changes via git diff stats
- Escalation signals

## Privacy Rules
1. Do NOT capture conversation content
2. Do NOT capture file contents
3. Only capture: timestamps, durations, counts, git stats
4. All data stays local in .praxis/

## Manual Logging
After significant tasks: `praxis log "desc" -d MIN -m MODEL -q 1-5 -i N -h N`
Governance events: `praxis govern "description"`

---
*Generated by PRAXIS Universal Kit — OpenClaw Tier 1 Integration*
"""

_MEMORY_CONTENT = """\
<!-- PRAXIS-GOVERNANCE -->
# PRAXIS Memory Protocol — OpenClaw L4 Integration

## Purpose
Cross-session governance continuity. OpenClaw memory → PRAXIS L4.

## Memory Categories
- **Active Rules** — Governance rules currently applied in this workspace
- **Incident Log** — Past failures and resolutions
- **Sprint Patterns** — Recurring workflow patterns worth preserving
- **Open Questions** — Decisions deferred to future sessions

## Memory Hygiene
1. Prune entries older than 30 days if no longer relevant
2. Consolidate duplicate patterns into one canonical rule
3. Tag each entry with creation date and last-referenced sprint
4. Do not store file contents or sensitive data — context pointers only

## PRAXIS-L4 Events
Run `praxis govern "rule_created: [description]"` when:
- A new persistent rule emerges from a sprint
- A pattern repeats 3+ times across sessions
- An incident requires a standing prevention rule

---
*Generated by PRAXIS Universal Kit — OpenClaw Tier 1 Integration*
"""


class OpenClawAdapter(PraxisAdapter):
    """PRAXIS adapter for OpenClaw (Tier 1 — deep integration)."""

    PLATFORM_ID = "openclaw"
    _OPENCLAW_HOME = Path.home() / ".openclaw"

    def detect(self) -> bool:
        if self._OPENCLAW_HOME.is_dir():
            return True
        if shutil.which("openclaw") is not None:
            return True
        if os.environ.get("OPENCLAW_HOME"):
            return True
        return False

    def inject_governance(
        self,
        templates_dir: Path,
        workspace_dir: Path,
    ) -> List[str]:
        created: List[str] = []

        soul = self._soul(templates_dir)
        agents = self._agents(templates_dir)
        memory_tmpl = self._memory(templates_dir)

        # Wrap template content with PRAXIS marker if not a placeholder
        def _wrap(header: str, body: str) -> str:
            if "[Template not found" in body:
                return header  # header-only if template missing
            return header + body

        soul_content = _wrap(
            f"{_MARKER}\n# PRAXIS Soul — OpenClaw Integration\n\n"
            "> PRAXIS Research Study active. Log: `praxis log`\n\n",
            soul,
        )
        agents_content = _wrap(
            f"{_MARKER}\n# PRAXIS Agents — OpenClaw Integration\n\n"
            "> Governance active. Log events: `praxis govern 'description'`\n\n",
            agents,
        )
        memory_content = (
            memory_tmpl if "[Template not found" not in memory_tmpl else _MEMORY_CONTENT
        )

        files: List[tuple] = [
            (workspace_dir / "SOUL.md",      soul_content),
            (workspace_dir / "AGENTS.md",    agents_content),
            (workspace_dir / "HEARTBEAT.md", _HEARTBEAT_CONTENT),
            (workspace_dir / "MEMORY.md",    memory_content),
        ]

        for dest, content in files:
            if dest.is_file():
                existing = dest.read_text(encoding="utf-8")
                if _MARKER not in existing:
                    dest.write_text(existing.rstrip() + "\n\n---\n\n" + content, encoding="utf-8")
                    created.append(f"{dest} (updated)")
            else:
                _write_file(dest, content)
                created.append(str(dest))

        # Register cron reminder (Unix only, best-effort)
        _register_cron_reminder(workspace_dir)

        return created

    def remove_governance(self, workspace_dir: Path) -> List[str]:
        removed: List[str] = []
        for name in ("SOUL.md", "AGENTS.md", "HEARTBEAT.md", "MEMORY.md"):
            dest = workspace_dir / name
            if dest.is_file():
                text = dest.read_text(encoding="utf-8")
                if _MARKER in text:
                    if text.strip().startswith(_MARKER):
                        result = _remove_file(dest)
                        if result:
                            removed.append(result)
                    else:
                        idx = text.find("\n\n---\n\n" + _MARKER)
                        if idx != -1:
                            dest.write_text(text[:idx], encoding="utf-8")
                            removed.append(f"{dest} (governance section removed)")
        return removed

    def get_info(self) -> Dict[str, Any]:
        return {
            "id": self.PLATFORM_ID,
            "name": "OpenClaw",
            "tier": 1,
            "description": "Deep integration: cron, heartbeat, memory system maps to PRAXIS L4.",
            "governance_files": ["SOUL.md", "AGENTS.md", "HEARTBEAT.md", "MEMORY.md"],
            "instructions": (
                "SOUL.md, AGENTS.md, HEARTBEAT.md, and MEMORY.md have been created. "
                "OpenClaw will pick them up automatically. "
                "Edit SOUL.md to add your name, role, and personal governance principles."
            ),
            "detected_path": str(self._OPENCLAW_HOME) if self._OPENCLAW_HOME.is_dir() else None,
        }


def _register_cron_reminder(project_root: Path) -> None:
    """Register a daily 6 PM weekday cron reminder. Best-effort, silent on failure."""
    try:
        if os.name != "posix":
            return
        cron_tag = "# PRAXIS-metrics-reminder"
        cron_line = (
            f"0 18 * * 1-5 cd {project_root} && "
            f"python collector/praxis_cli.py status 2>/dev/null  {cron_tag}"
        )
        result = subprocess.run(
            ["crontab", "-l"],
            capture_output=True, text=True, timeout=5,
        )
        existing = result.stdout if result.returncode == 0 else ""
        if cron_tag in existing:
            return
        new_cron = existing.rstrip() + "\n" + cron_line + "\n"
        subprocess.run(["crontab", "-"], input=new_cron, text=True, timeout=5, check=True)
    except Exception:
        pass
